iCC_OPTS=-Wall
GCC=/usr/bin/gcc
BINDIR=../bin/

all: read_character binary

read_character:
	$(GCC) $(CC_OPTS) -o $(BINDIR)read_character read_character.c

binary:
	$(GCC) $(CC_OPTS) -o $(BINDIR)binary binary.c

	
