#!/usr/bin/env bash

# git convenience functions. 
#
# abbrevations to often used git commands. This should be easier on your 
# writsts. Include this file in your .porfile (preferred) or .bashrc.
#
# Obviously you need to have git installed, colordiff is also expected.
#
# EXIT CODES
#  1 - parameter error
#  2 - missing dependency (see error message)
#
# Author: 2013, Simon Wunderlin, <swunderlin@gmail.com>

# program usage
function push_usage() {
	cat <<- EOF
		Usage: push <message>
		
		Message is the commit message as usually provided to 
		$ git commit -a -m"<message>"
		
	EOF
}

function push() {
	# check if param 1, the message, is supplied
	if [[ "$#" -ne 1 ]]; then
		  echo "illegal number of parameters";
		  push_usage;
			echo "Aborting, exit code 1"
		  exit 1;
	fi

	git commit -am "$1" && git push
}

function diff() {
	if [[ ! `which colordiff` ]]; then
		echo "Please install colordiff"
		echo "Aborting, exit code 2"
		exit 2;
	fi
	
	git diff | colordiff | less -R;
}

#push;


