#!/usr/bin/env bash

# git convenience functions. 
#
# abbrevations to often used git commands. This should be easier on your 
# writsts. Include this file in your .porfile (preferred) or .bashrc.
#
# Obviously you need to have git installed, meld and giggle is also expected.
#
# EXIT CODES
#  1 - parameter error
#  2 - missing dependency (see error message)
#
# Author: 2013, Simon Wunderlin, <swunderlin@gmail.com>

# program usage
function gpush_usage() {
	cat <<- EOF
		Usage: push <message>
		
		Message is the commit message as usually provided to 
		$ git commit -a -m"<message>"
		
	EOF
}

function gcommit() {
	if [[ "$#" -ne 1 ]]; then
		meld .
	else
		meld "$@"
	fi
}

function gpush() {
	# check if param 1, the message, is supplied
	if [[ "$#" -ne 1 ]]; then
		  echo "illegal number of parameters";
		  gpush_usage;
		  echo ""
			echo "Aborting, exit code 1"
		  return 1;
	fi

	git commit -am "$1" && git push
}

function gdiff() {
	if [[ ! `which meld` ]]; then
		echo "Please install meld"
		echo ""
		echo "Aborting, exit code 2"
		return 2;
	fi
	
	#git diff | colordiff | less -R;
	git difftool -y -t meld;
}

function gmerge() {
	if [[ ! `which meld` ]]; then
		echo "Please install meld"
		echo "Aborting, exit code 2"
		return 2;
	fi
	
	git mergetool -y -t meld
}

function ghistory() {
	if [[ ! `which giggle` ]]; then
		echo "Please install giggle"
		echo ""
		echo "Aborting, exit code 2"
		return 2;
	fi
	
	giggle .
}

alias gc=gcommit
alias gd=gdiff
alias gp=gpush
alias gm=gmerge
alias gh=ghistory
alias gs="git status"

#push;




